

services:
  db-test:
    image: postgres:15-alpine
    env_file:
      - .env.test
    ports:
      - "5432:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        echo '🔄 Waiting for test database...' &&
        python wait_for_test_db.py &&
        echo '🧪 Running tests...' &&
        pytest tests/ -v --tb=short --asyncio-mode=auto
      "
    depends_on:
      db-test:
        condition: service_healthy
    networks:
      - test-network

volumes:
  test_db_data:

networks:
  test-network:
    driver: bridge